### PR TITLE
Replace JSHint with ESLint

### PR DESCRIPTION
**Pull request by zeljkofilipin**
So far only the basic setup. Far from done yet.

### CODE REVIEW

**Comment by zeljkofilipin** [comment]
Fixed a lot of `Parsing error` errors. Still a lot of `space-in-parens` errors.

**Comment by zeljkofilipin** [comment]
Hm, looks like there are 2409 (!) `space-in-parens` errors, out of 3524 total, or 68%.

    $ npx eslint . | ack -c space-in-parens
    2409

    $ npx eslint .
    ...
    ✖ 3524 problems (3524 errors, 0 warnings)

**Comment by zeljkofilipin** [comment]
Looks like all spacing problems (space-in-parens, space-before-function-paren, array-bracket-spacing...) are 83% (2909/3524).

    $ npx eslint . | ack -c spac
    2909

**Comment by zeljkofilipin** [comment]
List of problems

```
$ npx eslint-nibble .

35 files checked.  0 passed.  35 failed.  0 warnings.  3361 errors.

? Which rule would you like to fix? 
  array-bracket-spacing:         32|  
  block-spacing:                  2| 
  brace-style:                   35|  
  comma-dangle:                   4| 
  comma-spacing:                  1| 
  computed-property-spacing:    121|      
  curly:                          9| 
  dot-location:                  16| 
  dot-notation:                   1| 
❯ indent:                       140|       
  key-spacing:                    2| 
  keyword-spacing:                9| 
  linebreak-style:              123|      
  new-cap:                       40|  
  no-console:                    56|   
  no-mixed-spaces-and-tabs:       1| 
  no-multi-spaces:                3| 
  no-multiple-empty-lines:        9| 
  no-trailing-spaces:             1| 
  no-underscore-dangle:           4| 
  no-unused-vars:                15| 
  no-use-before-define:           3| 
  no-useless-escape:              2| 
  object-curly-spacing:           6| 
  one-var:                       28|  
  quote-props:                    4| 
  quotes:                        50|   
  space-before-blocks:           31|  
  space-before-function-paren:  185|         
  space-in-parens:             2409|                                                                                                         
  space-infix-ops:                5| 
  spaced-comment:                12| 
  vars-on-top:                    2| 
```

**Comment by zeljkofilipin** [comment]
I am not sure how to proceed. Should I fix the problems (there will be a few big diffs) or configure eslint so it does not complain about white-space?

**Comment by macbre** [comment]
@zeljkofilipin, thanks for this PR. Yes, please ignore `white-space` for now.

We may want to run properly configured [`js-beautify`](https://github.com/beautify-web/js-beautify) over nodemw code.

**Comment by zeljkofilipin** [comment]
@macbre eslint can fix the code, there is no need for another tool.

I will start cleaning up, leaving white-space until the end.

**Comment by zeljkofilipin** [comment]
I have disabled all failing ESLint rules. I will enable a rule and fix it per commit, so the build stays green.

**Comment by zeljkofilipin** [comment]
All easy non-white-space fixes are made. I can continue if it looks good.

**Comment by zeljkofilipin** [comment]
This is what is left:

```
$ npx eslint-nibble .

35 files checked.  0 passed.  35 failed.  3122 warnings.  0 errors.

? Which rule would you like to fix? (Use arrow keys)
❯ array-bracket-spacing:         32|  
  block-spacing:                 20| 
  comma-spacing:                  1| 
  computed-property-spacing:    119|      
  indent:                       136|       
  key-spacing:                    2| 
  keyword-spacing:                9| 
  new-cap:                       40|  
  no-console:                    56|   
  no-mixed-spaces-and-tabs:       1| 
  no-multi-spaces:                3| 
  no-trailing-spaces:             1| 
  no-underscore-dangle:           4| 
  no-unused-vars:                15| 
  no-use-before-define:           3| 
  no-useless-escape:              2| 
  object-curly-spacing:           6| 
  one-var:                       28|  
  space-before-blocks:           31|  
  space-before-function-paren:  185|         
  space-in-parens:             2409|                                                                                                         
  space-infix-ops:                5| 
  spaced-comment:                12| 
  vars-on-top:                    2| 
```

**Comment by zeljkofilipin** [comment]
I have fixed a few small white-space errors.

TODO:

```
$ npx eslint-nibble .

35 files checked.  0 passed.  35 failed.  3116 warnings.  0 errors.

? Which rule would you like to fix? 
  array-bracket-spacing:         32|  
❯ block-spacing:                 20| 
  computed-property-spacing:    119|      
  indent:                       136|       
  key-spacing:                    2| 
  keyword-spacing:                9| 
  new-cap:                       40|  
  no-console:                    56|   
  no-underscore-dangle:           4| 
  no-unused-vars:                15| 
  no-use-before-define:           3| 
  no-useless-escape:              2| 
  object-curly-spacing:           6| 
  one-var:                       28|  
  space-before-blocks:           31|  
  space-before-function-paren:  185|         
  space-in-parens:             2409|                                                                                                         
  space-infix-ops:                5| 
  spaced-comment:                12| 
  vars-on-top:                    2| 
```

**Comment by zeljkofilipin** [comment]
Fixed a few more errors. Let me know if you have any comments so far.

TODO:

```
$ npx eslint-nibble .

35 files checked.  0 passed.  35 failed.  3002 warnings.  0 errors.

? Which rule would you like to fix? (Use arrow keys)
❯ array-bracket-spacing:         32|  
  block-spacing:                 20| 
  computed-property-spacing:    119|      
  indent:                       136|       
  key-spacing:                    2| 
  keyword-spacing:                9| 
  new-cap:                       40|  
  no-underscore-dangle:           4| 
  object-curly-spacing:           6| 
  one-var:                       28|  
  space-before-blocks:           31|  
  space-before-function-paren:  185|         
  space-in-parens:             2385|                                                                                                         
  space-infix-ops:                5| 
```

**Comment by macbre** [comment]
@zeljkofilipin, this looks great! Thanks.

**Comment by zeljkofilipin** [comment]
A few more fixes. Looks good so far?

TODO:

```
$ npx eslint-nibble .

35 files checked.  0 passed.  35 failed.  2457 warnings.  0 errors.

? Which rule would you like to fix? (Use arrow keys)
❯ new-cap:                40|  
  no-underscore-dangle:    4| 
  one-var:                28|  
  space-in-parens:      2385|      
```

**Review by macbre — APPROVED** [review]
This looks great!

**Comment by zeljkofilipin** [comment]
TODO:

```
$ npx eslint-nibble .

35 files checked.  0 passed.  35 failed.  2417 warnings.  0 errors.

? Which rule would you like to fix? (Use arrow keys)
❯ no-underscore-dangle:    4| 
  one-var:                28|  
  space-in-parens:      2385|
```

**Comment by zeljkofilipin** [comment]
TODO:

```
$ npx eslint-nibble .

35 files checked.  0 passed.  35 failed.  2389 warnings.  0 errors.

? Which rule would you like to fix? (Use arrow keys)
❯ no-underscore-dangle:    4| 
  space-in-parens:      2385|
```

**Comment by zeljkofilipin** [comment]
I am not sure what to do with remaining two.

`no-underscore-dangle` is about `_mwVersion` in [lib/bot.js#L1028-L1048 ](https://github.com/macbre/nodemw/blob/devel/lib/bot.js#L1028-L1048).

```
$ npx eslint-nibble .

35 files checked.  0 passed.  35 failed.  2389 warnings.  0 errors.

? Which rule would you like to fix? no-underscore-dangle

  ⚠  http://eslint.org/docs/rules/no-underscore-dangle  Unexpected dangling '_' in '_mwVersion'  
  /Users/z/Documents/github/zeljkofilipin/nodemw/lib/bot.js:999:15
  			if (typeof this._mwVersion !== 'undefined') {
  			            ^
  ⚠  http://eslint.org/docs/rules/no-underscore-dangle  Unexpected dangling '_' in '_mwVersion'  
  /Users/z/Documents/github/zeljkofilipin/nodemw/lib/bot.js:1000:20
  				callback(null, this._mwVersion);
  				                ^
  ⚠  http://eslint.org/docs/rules/no-underscore-dangle  Unexpected dangling '_' in '_mwVersion'  
  /Users/z/Documents/github/zeljkofilipin/nodemw/lib/bot.js:1018:5
  				this._mwVersion = version;
  				 ^
  ⚠  http://eslint.org/docs/rules/no-underscore-dangle  Unexpected dangling '_' in '_mwVersion'  
  /Users/z/Documents/github/zeljkofilipin/nodemw/lib/bot.js:1019:20
  				callback(null, this._mwVersion);
  				                ^
✘ 4 problems (0 errors, 4 warnings)

Warnings:
  4  http://eslint.org/docs/rules/no-underscore-dangle
```

Should I ignore it for those 4 lines?

**Comment by zeljkofilipin** [comment]
`space-in-parens` was trivial to fix. It's a big change, but easy to review. Let me know if you don't like it.

TODO:

```
$ npx eslint-nibble .

35 files checked.  34 passed.  1 failed.  4 warnings.  0 errors.

? Which rule would you like to fix? (Use arrow keys)
❯ no-underscore-dangle: 4|
```

**Comment by macbre** [comment]
> `no-underscore-dangle` is about `_mwVersion` in [lib/bot.js#L1028-L1048 ](https://github.com/macbre/nodemw/blob/devel/lib/bot.js#L1028-L1048).

@zeljkofilipin, let's just ignore this rule.

**Comment by zeljkofilipin** [comment]
ESLint is happy now. Let me know if anything else needs to be done.

**Comment by macbre** [comment]
This is great. Thanks for your changes, @zeljkofilipin !

**Pull request merged**
